### ISSUE TITLE
Problème avec les touches gauche / droite sur les subnav_links des premier et derniers éléments du menu

### ISSUE THREAD

**Issue by jbcordina** [nico3333fr/jquery-accessible-subnav-dropdown#2]
Un problème apparait lorsqu'on essaie d'utiliser les flèches gauche / droite pour la navigation dans les sous menu des premiers et derniers onglets. (exemple, je suis sur le sous menu du premier onglet, j'essaie d'aller à gauche et inversement pour le sous menu du dernier onglet).

Corrigé chez moi avec la correction suivante, remplacer la ligne 152
`$nav = $nav_link.parents('.js-nav-system__item');`
par
`$nav = $nav_link.parents('.js-nav-system');`

Merci beaucoup pour les différents plugins, c'est autant utile qu'instructif :)

**Comment by nico3333fr** [comment]
Hello,

effectivement, il y avait bien un souci qui m'avait échappé, et en fait deux.

Celui que tu mentionnes en premier, et ajoute en plus qu'une fois ce problème réglé, quand tu faisais "gauche" sur le sous-menu du premier onglet, ça sélectionnait le dernier élément du dernier sous-menu, au lieu de sélectionner le premier.

Ligne 227 :

```
$subnav_prev.find( ".js-nav-system__subnav__item:last-child ").children( ".js-nav-system__subnav__link" ).focus();
```

devient 

```
$subnav_prev.find( ".js-nav-system__subnav__item:first-child ").children( ".js-nav-system__subnav__link" ).focus();
```

Donc double merci pour m'avoir trouvé ce bug :)
