### ISSUE TITLE
3 niveaux de menu ?

### ISSUE THREAD

**Issue by juliemoynat** [nico3333fr/jquery-accessible-subnav-dropdown#7]
Bonjour,

Est-il possible de faire fonctionner facilement ce menu pour un menu à 3 niveaux ?

**Comment by nico3333fr** [comment]
Hello,

nope, pas possible. Ceci dit, regarde dans les PR, y a un gros refactoring qui p-e le permet (j'ai jamais eu le temps de m'y pencher, honte à moi).

**Comment by juliemoynat** [comment]
Merci pour ta réponse. De toutes façons, après quelques réflexions et recherches, il s'avère que ce n'est pas une bonne idée pour l'expérience utilisateur.

**Comment by nico3333fr** [comment]
@juliemoynat oh oui, ça pose tellement de problèmes qu'en général ça en crée plus que ça n'en résout. :)
