### ISSUE TITLE
Tab menu not work in mac 10.12 safari 10

### ISSUE THREAD

**Issue by yonglas-surfcode** [nico3333fr/jquery-accessible-subnav-dropdown#9]
I have this running on my test server and as far as I can tell it working on Windows, Android and iPhone, however, it’s (Navigate with tab and arrows) not working on my Mac PC.

**Comment by yonglas-surfcode** [comment]
This issue is solve only if you change browser setting . (read more here http://www.weba11y.com/blog/2014/07/07/keyboard-navigation-in-mac-browsers/)
go to Safari > preference > advanced > and click press Tab highlight...
![image](https://user-images.githubusercontent.com/1401159/31055868-546774d6-a6d2-11e7-9ccf-bc8b9545b167.png)

Please test and let me know if you have another solution that not force user to change his setting...

**Comment by nico3333fr** [comment]
Hi,

after checking with accessibility experts like @goetsu I confirm that unfortunately, there is nothing we can do for this issue. :-|

Anyway, thank for having pointed it out. 👍
